
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor:
  - platform: template
    sensors:
      vpd:
        friendly_name: "Vapor Pressure Deficit"
        unit_of_measurement: "kPa"
        value_template: >
          {% set T = states('sensor.sonoff_snzb_02d_temperatur') | float %}
          {% set RH = states('sensor.sonoff_snzb_02d_luftfeuchtigkeit') | float %}
          {% set SVP = 0.6108 * (2.71828 ** ((17.27 * T) / (T + 237.3))) %}
          {% set VPD = SVP * (1 - (RH / 100.0)) %}
          {{ VPD | round(2) }}
          
          
          
          type: custom:ha-vpd-chart
sensors:
  - temperature: sensor.sonoff_snzb_02d_temperatur
    humidity:  sensor.sonoff_snzb_02d_luftfeuchtigkei
    name: Tent 1
  - temperature: sensor.temperature_tent_2
    humidity: sensor.humidity_tent_2
    name: Tent 2
    


# https://github.com/kalkih/mini-graph-card?tab=readme-ov-file#add-resource-reference
 # [Mini Graph Card HACS]
resources:
  - url: /local/mini-graph-card-bundle.js?v=0.12.1
    type: module
